-- Não dá
SELECT * FROM CITY;
SELECT * FROM TEAM;
SELECT * FROM BOOT_WINNERS;

-- Dá
INSERT INTO CITY VALUES
(500, 'Porto Alegre', 5);

INSERT INTO STADIUM VALUES
(500, 'Estadio Beira-Rio', 50842, 500);

-- Também não dá
DELETE FROM CITY WHERE ID_CITY = 500;
DELETE FROM STADIUM WHERE ID_STADIUM = 500;